### ISSUE TITLE
Fix versions on gemfile

### ISSUE THREAD

**Issue by oswaldoferreira** [algorich/notifly#58]
Just bundle'd the project and got this:
 
![captura de tela 2015-05-27 as 09 18 30](https://cloud.githubusercontent.com/assets/1419991/7851002/7d5da0c0-04bf-11e5-88ed-bcf1d31518a9.png)

I'm running 2.2.0 ruby.

I would suggest keeping the gem versions fixed, like explained on this post:

https://robots.thoughtbot.com/a-healthy-bundle

TL;DR: This practice discourages the act of updating gems ASAP, but, it decreases quantity of unexpected bugs.

**Comment by RafaelMCarvalho** [comment]
Weird. I'll try to fix this and cite you when done.
Thanks for your feedback =)
